### ISSUE TITLE
Implementación de responsive design

### ISSUE THREAD

**Issue by eliassaso** [Blanco009/Clase-IS043#1]
@Blanco009  Te parece si implementamos los porcentajes en cada una de estas clases para que pueda quedar en cumplimiento? es decir, nos apoyamos en este mismo proyecto, solo lo hacemos con porcentajes en cada clase para lograr el responsive design.

Ejemplo, el content no tiene porcentaje y about no existe como clase en el archivo .css:

https://github.com/Blanco009/Clase-IS043/blob/a91df592bba027fe0c6276c820b19ad22c075c03/paginaWebPractica/index.html#L56

**Comment by Blanco009** [comment]
Listo profe lo que hice fue borrar el archivo css y comenzar uno desde cero
para ver si entendía mejor, porque con el que estaba trabajando me dio
muchos problemas.
Creo que logre que fuera mas responsive, porque lo probé con celulares y
ipads.

**Comment by eliassaso** [comment]
Voy a dar el issue por cerrado pero recuerda eliminar la implementación de:
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
